#-------------------------------
# General Site Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: RudeOps

#-------------------------------
# Build Settings

date_format: "%B %-d, %Y"

markdown: kramdown
permalink: /:year-:month-:day-:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/newsletter/page/:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /newsletter/:year-:month-:day-:title/
  projects:
    output: true
    permalink: /project/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

sass:
  sass_dir: _sass
  style: expanded